### ISSUE TITLE
Villager Edit crash?

### ISSUE THREAD

**Issue by realMBite** [Slattz/NLTK#2]
(I just started using the editor and don't know much about it). I opened up the editor and pressed the "Villagers" button. I had 2 open slots for new villagers at the time. I pressed on one of them and I couldn't press on any others. I pressed the B button to exit the screen and it crashed. Am I doing something wrong, or is this a bug?

**Comment by Slattz** [comment]
Are you on the latest nightly?

**Comment by realMBite** [comment]
The version I installed was the cia version of the Nightly Build.

**Comment by Slattz** [comment]
This has been fixed in commit ab2fa74 🙂 

thanks for reporting the issue 👍
